//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recepty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingridients
    {
        public int Ing_Id { get; set; }
        public string Ing_Name { get; set; }
        public string Ing_Weight { get; set; }
        public double ING_Price { get; set; }
    }
}
