//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recepty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int Rec_Id { get; set; }
        public string Rec_Name { get; set; }
        public string Ing_List { get; set; }
        public double Rec_Price { get; set; }
        public Nullable<int> Cook_Met_Id { get; set; }
        public string Rec_Pic { get; set; }
        public string Ingr_Count { get; set; }
    
        public virtual Cooking_Method Cooking_Method { get; set; }
    }
}
